bin.includes = META-INF/,\
               .,\
               OSGI-INF/,\
               libx/,\
               libx/mssql-jdbc-12.6.3.jre11.jar,\
               OSGI-INF/CustomInfoFactory.xml
source.. = src/
output.. = target/classes/
