package za.co.ntier.wsp_atr.report.process;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Properties;

import org.adempiere.base.annotation.Parameter;
import org.adempiere.exceptions.AdempiereException;
import org.adempiere.util.Callback;
import org.adempiere.webui.apps.BackgroundJob;
import org.compiere.model.MPInstance;
import org.compiere.model.MPInstancePara;
import org.compiere.model.MProcess;
import org.compiere.model.MTable;
import org.compiere.process.ProcessInfo;
import org.compiere.process.SvrProcess;
import org.compiere.util.DB;
import org.compiere.util.Env;
import org.compiere.util.Util;

import za.co.ntier.wsp_atr.models.I_ZZ_WSP_ATR_Submitted;
import za.co.ntier.wsp_atr.models.X_ZZ_WSP_ATR_Report;
import za.co.ntier.wsp_atr.models.X_ZZ_WSP_ATR_Submitted;
import za.ntier.models.MZZWSPATRSubmitted;

@org.adempiere.base.annotation.Process(
		name = "za.co.ntier.wsp_atr.report.process.GenerateWspAtrReportProcess")
public class GenerateWspAtrReportProcess extends SvrProcess {
	
	@Parameter(name = "ZZ_ConsolidatedSubmission")
	private boolean consolidatedSubmission;
	
	@Parameter(name = "ZZ_Only_Sub_Levy_Orgs")
	private boolean p_ZZ_Only_Sub_Levy_Orgs;

	private int p_ZZ_WSP_ATR_Submitted_ID;
	private Properties ctx = null;
	private static final String PROCESS_PRINT_REPORT_UU = "0875c375-6e37-49fb-a5c0-798529189260";

	/** Leading part of the generated PDF's file name, as specified by the business. */
	private static final String REPORT_FILE_BASE_NAME = "WORKPLACE_SKILLS_PLAN_AND_ANNUAL_TRAINING_REPORT";
	
	
	@Override
	protected void prepare() {
		p_ZZ_WSP_ATR_Submitted_ID = getRecord_ID();
		if (p_ZZ_WSP_ATR_Submitted_ID <= 0) {
			throw new IllegalArgumentException("No ZZ_WSP_ATR_Submitted record selected.");
		}
		ctx = getCtx();
	}

	@Override
	protected String doIt() throws Exception {


		// Load the submitted record (window record)
		MZZWSPATRSubmitted submitted =
				(MZZWSPATRSubmitted) MTable.get(getCtx(), I_ZZ_WSP_ATR_Submitted.Table_ID)
				.getPO(p_ZZ_WSP_ATR_Submitted_ID, get_TrxName());

		if (submitted == null) {
			throw new IllegalStateException("ZZ_WSP_ATR_Submitted not found for ID=" + p_ZZ_WSP_ATR_Submitted_ID);
		}

		// Step 1: try find latest existing report matching the same criteria
		X_ZZ_WSP_ATR_Report report = findExistingReport(submitted,consolidatedSubmission,p_ZZ_Only_Sub_Levy_Orgs);

		boolean isNewReport = false;
		boolean shouldCreateNewReport = report == null
				|| X_ZZ_WSP_ATR_Submitted.ZZ_DOCSTATUS_Imported.equals(submitted.getZZ_DocStatus());

		if (shouldCreateNewReport) {
		    // Imported submissions always create a fresh report record
		    report = createReport(submitted,consolidatedSubmission,p_ZZ_Only_Sub_Levy_Orgs);
		    isNewReport = true;
		}

		// Step 2: only build sections if this is a NEW report
		int totalInserted = 0;

		if (isNewReport) {
		    List<IReportSectionBuilder> builders =
		        ReportSectionBuilderFactory.getBuilders(getCtx(), submitted);

		    for (IReportSectionBuilder b : builders) {
		        ReportBuildResult r = b.build(report, submitted,consolidatedSubmission,p_ZZ_Only_Sub_Levy_Orgs, get_TrxName());
		        totalInserted += r.getInsertedCount();
		        addLog("Section " + b.getSectionCode() +
		               " - " + b.getName() +
		               ": inserted " + r.getInsertedCount());
		    }
		}

		// Step 3: always print (existing or new)
		runProcessInBackgroundWithIntParam(
		    PROCESS_PRINT_REPORT_UU,
		    "ZZ_WSP_ATR_Report_ID",
		    report.getZZ_WSP_ATR_Report_ID(),
		    submitted.getZZ_WSP_ATR_Submitted_ID(),
		    buildReportPdfPath(submitted)
		);

		if (isNewReport) {
		    return "Created report ID=" + report.getZZ_WSP_ATR_Report_ID()
		            + " for submitted ID=" + p_ZZ_WSP_ATR_Submitted_ID
		            + ". Total inserted rows=" + totalInserted;
		} else {
		    return "Existing report ID=" + report.getZZ_WSP_ATR_Report_ID()
		            + " found. Report re-printed.";
		}
	}

	private X_ZZ_WSP_ATR_Report createReport(MZZWSPATRSubmitted submitted,boolean consolidatedSubmission,boolean p_ZZ_Only_Sub_Levy_Orgs) {
		X_ZZ_WSP_ATR_Report report = new X_ZZ_WSP_ATR_Report(getCtx(), 0, get_TrxName());

		// Name/Description: make it meaningful for your users
		String name = "WSP/ATR Report - Submitted #" + submitted.getZZ_WSP_ATR_Submitted_ID();
		report.setName(name);
		report.setDescription("Generated by process on " + Env.getContextAsDate(getCtx(), "#Date"));
		report.setDatePrinted(Env.getContextAsDate(getCtx(), "#Date"));

		report.setZZ_WSP_ATR_Submitted_ID(submitted.getZZ_WSP_ATR_Submitted_ID());

		// optionally set AD_Client_ID / AD_Org_ID explicitly if your table requires it
		// report.setAD_Org_ID(submitted.getAD_Org_ID());
		report.setZZ_ConsolidatedSubmission(consolidatedSubmission);
		report.setZZ_Only_Sub_Levy_Orgs(p_ZZ_Only_Sub_Levy_Orgs);

		if (!report.save()) {
			throw new IllegalStateException("Failed to create ZZ_WSP_ATR_Report: "); // + report.getProcessMsg());
		}
		return report;
	}
	
	private X_ZZ_WSP_ATR_Report findExistingReport(MZZWSPATRSubmitted submitted,boolean consolidatedSubmission,boolean p_ZZ_Only_Sub_Levy_Orgs) {

	    int submittedId = submitted.getZZ_WSP_ATR_Submitted_ID();

	    int existingReportId = DB.getSQLValueEx(
	        get_TrxName(),
	        "SELECT ZZ_WSP_ATR_Report_ID " +
	        " FROM ZZ_WSP_ATR_Report " +
	        " WHERE ZZ_WSP_ATR_Submitted_ID=? " +
	        " AND ZZ_ConsolidatedSubmission=? " +
	        " AND ZZ_Only_Sub_Levy_Orgs=? " +
	        " AND IsActive='Y' " +
	        " ORDER BY Created DESC, ZZ_WSP_ATR_Report_ID DESC " +
	        " FETCH FIRST 1 ROWS ONLY",
	        submittedId,
	        consolidatedSubmission ? "Y" : "N",
	        p_ZZ_Only_Sub_Levy_Orgs ? "Y" : "N"
	    );

	    if (existingReportId > 0) {
	    	X_ZZ_WSP_ATR_Report report = new X_ZZ_WSP_ATR_Report(getCtx(), existingReportId, get_TrxName());
	    	report.setDatePrinted(Env.getContextAsDate(getCtx(), "#Date"));
	    	if (!report.save()) {
				throw new IllegalStateException("Failed to save ZZ_WSP_ATR_Report: "); // + report.getProcessMsg());
			}
	    	return report;
	    }

	    return null;
	}


	/**
	 * Builds the file name the generated PDF is written to, e.g.
	 * WORKPLACE_SKILLS_PLAN_AND_ANNUAL_TRAINING_REPORT_L8767868687_202610010953.pdf
	 *
	 * Without this the shared Jasper starter falls back to
	 * File.createTempFile(makePrefix(reportName), ".pdf"), which appends a random long - the
	 * meaningless 19-20 digit number users were seeing. DazzleReportStarter honours
	 * ProcessInfo.getPDFFileName() when it is set, so the name is fixed here rather than in that
	 * shared code, which names every Jasper report in the system.
	 *
	 * The SDL number is the PARENT's: a consolidated report carries its children in the detail,
	 * not in the file name.
	 *
	 * The file goes in a freshly created temp DIRECTORY rather than being made unique itself.
	 * That keeps the readable name on the emailed attachment while making it impossible for two
	 * prints of the same submission in the same minute to overwrite each other's file.
	 *
	 * Returns null if the directory cannot be created, which simply restores the old behaviour
	 * rather than failing the print.
	 */
	private String buildReportPdfPath(MZZWSPATRSubmitted submitted) {
		String sdlNo = DB.getSQLValueStringEx(get_TrxName(),
				"SELECT bp.value "
				+ "FROM adempiere.zzsdforganisation so "
				+ "JOIN adempiere.c_bpartner bp ON bp.c_bpartner_id = so.c_bpartner_id "
				+ "WHERE so.zzsdforganisation_id = ?",
				submitted.getZZSdfOrganisation_ID());

		StringBuilder fileName = new StringBuilder(REPORT_FILE_BASE_NAME);
		if (!Util.isEmpty(sdlNo, true)) {
			fileName.append('_').append(sdlNo.trim());
		}
		fileName.append('_').append(new SimpleDateFormat("yyyyMMddHHmm").format(new Date()));
		fileName.append(".pdf");

		try {
			Path dir = Files.createTempDirectory("wspatr_report_");
			return dir.resolve(fileName.toString()).toString();
		} catch (IOException e) {
			log.warning("Could not create temp directory for the report PDF, falling back to the"
					+ " default generated name: " + e.getMessage());
			return null;
		}
	}

	private void runProcessInBackgroundWithIntParam(String adProcessUU, String paramName, int paramValue,
			int recordIdForInstance, String pdfFileName) {
		MProcess proc = MProcess.get(ctx, adProcessUU);
		if (proc == null || proc.getAD_Process_ID() <= 0) throw new AdempiereException("Process not found (UU=" + adProcessUU + ")");

		ProcessInfo pi = new ProcessInfo(proc.getName(), proc.getAD_Process_ID());
		pi.setAD_User_ID(Env.getAD_User_ID(ctx));
		pi.setAD_Client_ID(Env.getAD_Client_ID(ctx));
		pi.setTable_ID(MTable.getTable_ID(X_ZZ_WSP_ATR_Report.Table_Name));
		pi.setRecord_ID(recordIdForInstance);
		pi.setAD_Process_UU(proc.getAD_Process_UU());
		if (pdfFileName != null) {
			pi.setPDFFileName(pdfFileName);
		}

		MPInstance instance = new MPInstance(ctx, proc.getAD_Process_ID(), 0, recordIdForInstance, null);
		instance.setIsRunAsJob(true);
		instance.setNotificationType(MPInstance.NOTIFICATIONTYPE_EMailPlusNotice);
		instance.saveEx();

		pi.setAD_PInstance_ID(instance.getAD_PInstance_ID());

		Callback<Integer> createInstanceParaCallback = id -> {
			if (id > 0) {
				MPInstance instanceLater = new MPInstance(Env.getCtx(), id, null);
				MPInstancePara para = new MPInstancePara(instanceLater, 10);
				para.setParameterName(paramName);
				para.setP_Number(paramValue);
				para.saveEx();
			}
		};

		BackgroundJob.create(pi)
		.withContext(ctx)
		.withNotificationType(instance.getNotificationType())
		.withInitialDelay(250)
		.run(createInstanceParaCallback);
	}
}
