package za.co.ntier.wsp_atr.report.process;

import java.util.List;

import org.compiere.process.SvrProcess;
import org.compiere.util.Env;

import za.co.ntier.wsp_atr.models.I_ZZ_WSP_ATR_Submitted;
import za.co.ntier.wsp_atr.models.X_ZZ_WSP_ATR_Report;
import org.compiere.model.MTable;

@org.adempiere.base.annotation.Process(
		name = "za.co.ntier.wsp_atr.report.process.GenerateWspAtrReportProcess")
public class GenerateWspAtrReportProcess extends SvrProcess {

    private int p_ZZ_WSP_ATR_Submitted_ID;

    @Override
    protected void prepare() {
        p_ZZ_WSP_ATR_Submitted_ID = getRecord_ID();
        if (p_ZZ_WSP_ATR_Submitted_ID <= 0) {
            throw new IllegalArgumentException("No ZZ_WSP_ATR_Submitted record selected.");
        }
    }

    @Override
    protected String doIt() throws Exception {

        // Load the submitted record (window record)
        I_ZZ_WSP_ATR_Submitted submitted =
                (I_ZZ_WSP_ATR_Submitted) MTable.get(getCtx(), I_ZZ_WSP_ATR_Submitted.Table_ID)
                        .getPO(p_ZZ_WSP_ATR_Submitted_ID, get_TrxName());

        if (submitted == null) {
            throw new IllegalStateException("ZZ_WSP_ATR_Submitted not found for ID=" + p_ZZ_WSP_ATR_Submitted_ID);
        }

        // Step 1: create report header linked to submitted
        X_ZZ_WSP_ATR_Report report = createReport(submitted);

        // Step 2: run all registered section builders (factory/registry)
        List<IReportSectionBuilder> builders = ReportSectionBuilderFactory.getBuilders(getCtx(), submitted);

        int totalInserted = 0;
        for (IReportSectionBuilder b : builders) {
            ReportBuildResult r = b.build(report, submitted, get_TrxName());
            totalInserted += r.getInsertedCount();
            addLog("Section " + b.getSectionCode() + " - " + b.getName() + ": inserted " + r.getInsertedCount());
        }

        return "Created report ID=" + report.getZZ_WSP_ATR_Report_ID()
                + " for submitted ID=" + p_ZZ_WSP_ATR_Submitted_ID
                + ". Total inserted rows=" + totalInserted;
    }

    private X_ZZ_WSP_ATR_Report createReport(I_ZZ_WSP_ATR_Submitted submitted) {
        X_ZZ_WSP_ATR_Report report = new X_ZZ_WSP_ATR_Report(getCtx(), 0, get_TrxName());

        // Name/Description: make it meaningful for your users
        String name = "WSP/ATR Report - Submitted #" + submitted.getZZ_WSP_ATR_Submitted_ID();
        report.setName(name);
        report.setDescription("Generated by process on " + Env.getContextAsDate(getCtx(), "#Date"));

        report.setZZ_WSP_ATR_Submitted_ID(submitted.getZZ_WSP_ATR_Submitted_ID());

        // optionally set AD_Client_ID / AD_Org_ID explicitly if your table requires it
        // report.setAD_Org_ID(submitted.getAD_Org_ID());

        if (!report.save()) {
            throw new IllegalStateException("Failed to create ZZ_WSP_ATR_Report: "); // + report.getProcessMsg());
        }
        return report;
    }
}
